Add workaround for Emacs<=25.3
integ test for Emacs25.3 failed due to undefined functions.

Error: the following functions are not known to be defined:
file-local-name, temporary-file-directory

This commit fixes the problem by reverting to the original codes when
the functions are not available.